### ISSUE TITLE
[spren_flutter 1.2.0, Android] fatal sentry exception while initializing

### ISSUE THREAD

**Issue by AErmek** [Elite-HRV/spren-vision-ios#9]
Hi, I wanted to try if new spren_flutter 1.2.0 version fixed [https://github.com/Elite-HRV/spren-vision-ios/issues/6](url) . But getting this fatal exception while initializing app: 

E/AndroidRuntime(16644): java.lang.RuntimeException: Unable to get provider io.sentry.android.core.SentryInitProvider: java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
E/AndroidRuntime(16644): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7774)
E/AndroidRuntime(16644): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7286)
E/AndroidRuntime(16644): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7026)
E/AndroidRuntime(16644): 	at android.app.ActivityThread.access$1800(ActivityThread.java:254)
E/AndroidRuntime(16644): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
E/AndroidRuntime(16644): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16644): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(16644): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(16644): 	at android.app.ActivityThread.main(ActivityThread.java:8210)
E/AndroidRuntime(16644): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16644): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(16644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(16644): Caused by: java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
E/AndroidRuntime(16644): 	at io.sentry.Sentry.initConfigurations(Sentry.java:199)
E/AndroidRuntime(16644): 	at io.sentry.Sentry.init(Sentry.java:169)
E/AndroidRuntime(16644): 	at io.sentry.Sentry.init(Sentry.java:117)
E/AndroidRuntime(16644): 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:83)
E/AndroidRuntime(16644): 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:52)
E/AndroidRuntime(16644): 	at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:27)
E/AndroidRuntime(16644): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2413)
E/AndroidRuntime(16644): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2383)
E/AndroidRuntime(16644): 	at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:44)
E/AndroidRuntime(16644): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7769)
E/AndroidRuntime(16644): 	... 11 more

**Comment by navasiloy** [comment]
Thanks @AErmek for posting this. We are going to release a fix for this very soon and will let you know!

**Comment by navasiloy** [comment]
@AErmek we've release `spren_flutter` 1.2.2 with the fix. Please, try it out.

**Comment by AErmek** [comment]
Hi, yep, this issue fixed

**Comment by AErmek** [comment]
But there is error while setTorchMode on Android

```
 I/flutter (31317): MissingPluginException(No implementation found for method setTorchMode on channel com.spren/spren_flutter_method)
I/flutter (31317): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
I/flutter (31317): <asynchronous suspension>
I/flutter (31317): #1      SprenFlutter.setTorchMode
package:spren_flutter/spren_flutter.dart:26
I/flutter (31317): <asynchronous suspension>
I/flutter (31317): #2      SprenMixin.sprenSetTorch
package:flutter_app/…/page/spren_mixin.dart:126
I/flutter (31317): <asynchronous suspension>
```

**Comment by AErmek** [comment]
I temporary disabled setTorhcMode method call. It goes further, 
for 1 second CameraViewOverlay shows on top of CameraViewAndroid. 
but then maybe CameraViewAndroid recreating himself and make CameraViewAndroid on top of Stack, so CameraViewOverlay not showing.
Here is stackTrace:

```
E/FrameEvents(10837): updateAcquireFence: Did not find frame.
D/SurfaceViewImpl(10837): Surface destroyed.
D/SurfaceViewImpl(10837): Surface invalidated androidx.camera.core.SurfaceRequest@18ac326
D/DeferrableSurface(10837): surface closed,  useCount=1 closed=true androidx.camera.core.SurfaceRequest$2@4eedb67
D/DeferrableSurface(10837): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@e4febb2
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Use cases [androidx.camera.core.Preview-fe8e0a13-f1ff-4ac9-ae61-2b2f464ff07524333146, androidx.camera.core.ImageAnalysis-0749f82a-0493-4bd3-9459-72f116bb052b11055499] now DETACHED for camera
D/UseCaseAttachState(10837): All use case: [] for camera: 0
I/flutter (10837): [4] HrvBloc.close()
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Resetting Capture Session
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Releasing session in state OPENED
D/UseCaseAttachState(10837): Active and attached use case: [] for camera: 0
E/BufferQueueProducer(10837): [SurfaceView[io.smooch.demoapp/io.smooch.demoapp.MainActivity]#5(BLAST Consumer)5](id:2a550000000b,api:4,p:1712,c:10837) queueBuffer: BufferQueue has been abandoned
D/UseCaseAttachState(10837): Active and attached use case: [] for camera: 0
W/Camera2CameraImpl(10837): Unable to find a repeating surface to attach to CaptureConfig
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Issue capture request
D/UseCaseAttachState(10837): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Closing camera.
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/CameraStateRegistry(10837): Recalculating open cameras:
D/CameraStateRegistry(10837): Camera                                       State
D/CameraStateRegistry(10837): -------------------------------------------------------------------
D/CameraStateRegistry(10837): Camera@b996289[id=0]                         CLOSING
D/CameraStateRegistry(10837): Camera@16999a[id=1]                          UNKNOWN
D/CameraStateRegistry(10837): -------------------------------------------------------------------
D/CameraStateRegistry(10837): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(10837): New public camera state CameraState{type=CLOSING, error=null} from CLOSING and null
D/CameraStateMachine(10837): Publishing new public camera state CameraState{type=CLOSING, error=null}
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Resetting Capture Session
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Releasing session in state CLOSING
D/CaptureSession(10837): onSessionFinished()
D/StreamStateObserver(10837): Update Preview stream state to IDLE
5
E/BufferQueueProducer(10837): [SurfaceView[io.smooch.demoapp/io.smooch.demoapp.MainActivity]#5(BLAST Consumer)5](id:2a550000000b,api:4,p:1712,c:10837) cancelBuffer: BufferQueue has been abandoned
W/libc    (10837): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal(10837): Camera 5 is not available. Ignore physical camera status change
E/CameraManagerGlobal(10837): Camera 6 is not available. Ignore physical camera status change
E/CameraManagerGlobal(10837): Camera 7 is not available. Ignore physical camera status change
W/libc    (10837): Access denied finding property "vendor.camera.aux.packagelist"
D/UseCaseAttachState(10837): Active and attached use case: [] for camera: 0
D/DeferrableSurface(10837): use count-1,  useCount=0 closed=true androidx.camera.core.SurfaceRequest$2@4eedb67
D/DeferrableSurface(10837): Surface no longer in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@4eedb67}
D/DeferrableSurface(10837): Surface terminated[total_surfaces=1, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@4eedb67}
D/DeferrableSurface(10837): use count-1,  useCount=0 closed=true androidx.camera.core.impl.ImmediateSurface@e4febb2
D/DeferrableSurface(10837): Surface no longer in use[total_surfaces=1, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@e4febb2}
D/DeferrableSurface(10837): Surface terminated[total_surfaces=0, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@e4febb2}
D/SurfaceViewImpl(10837): Safe to release surface.
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} CameraDevice.onClosed()
D/Camera2CameraImpl(10837): {Camera@b996289[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
D/CameraStateRegistry(10837): Recalculating open cameras:
D/CameraStateRegistry(10837): Camera                                       State
D/CameraStateRegistry(10837): -------------------------------------------------------------------
D/CameraStateRegistry(10837): Camera@b996289[id=0]                         CLOSED
D/CameraStateRegistry(10837): Camera@16999a[id=1]                          UNKNOWN
D/CameraStateRegistry(10837): -------------------------------------------------------------------
D/CameraStateRegistry(10837): Open count: 0 (Max allowed: 1)
D/CameraStateMachine(10837): New public camera state CameraState{type=CLOSED, error=null} from CLOSED and null
D/CameraStateMachine(10837): Publishing new public camera state CameraState{type=CLOSED, error=null}
D/OplusCamera2StatisticsManager(10837): addPreviewInfo, eventMap: {halLevel=3, preview_time=2696, face_count=0, cameraId=0, touchxy_value=76,64, pkgName=io.smooch.demoapp, apLevel=2}
D/OplusCamera2StatisticsManager(10837): addInfo, eventMap: {halLevel=3, cameraId=0, disconnectTime=1655457475607, pkgName=io.smooch.demoapp, connentTime=1655457472911, apLevel=2, timeCost=2696}
E/ActivityThread(10837): Failed to find provider info for com.oplus.statistics.provider
E/OplusStatistics--(10837): IllegalArgumentException:java.lang.IllegalArgumentException: Unknown URL content://com.oplus.statistics.provider/track_event
```

**Comment by navasiloy** [comment]
@AErmek this is known issue with Flutter 3 https://github.com/flutter/flutter/issues/103630 and is experienced with many other libs. We are using and testing it on Flutter 2 up to the time until it gets fixed.  Please, try it out and let us know know how it goes.

**Comment by navasiloy** [comment]
@AErmek do you still get an issue using `setTorchMode`?

**Comment by navasiloy** [comment]
closing as due to inactivity (spren_flutter 1.2.3 is the latest Flutter 2 solution for the moment)

**Comment by AErmek** [comment]
> @AErmek do you still get an issue using `setTorchMode`?

Sorry for late answer, I was on vacation. This problem on spren_flutter: ^1.3.0 still exist

**Comment by navasiloy** [comment]
@AErmek sure, NP! 
Can you, please, check `spren_flutter` version set in `pubspec.lock` in your app?

**Comment by AErmek** [comment]
> @AErmek sure, NP! Can you, please, check `spren_flutter` version set in `pubspec.lock` in your app?

@navasiloy here:

![image](https://user-images.githubusercontent.com/50573441/177470789-11afbbc9-f00b-4289-8de3-d68b59e53b63.png)

**Comment by navasiloy** [comment]
closing due to inactivity on this thread
